import { Course } from "./constants";

export const COURSES_UR: Course[] = [
  {
    slug: "beginner-ai-course",
    title: "Beginner AI Course — آرٹیفیشل انٹیلیجنس کا تعارف",
    shortTitle: "Beginner AI کورس",
    description:
      "اپنے AI سفر کا آغاز بالکل شروع سے کریں۔ آرٹیفیشل انٹیلیجنس کے بنیادی اصول سیکھیں، یہ سمجھیں کہ AI کیسے کام کرتا ہے، اور ماہر اساتذہ کی رہنمائی میں اپنے پہلے AI پروجیکٹس تیار کریں۔",
    level: "Beginner",
    duration: "8 ہفتے",
    ageGroup: "عمر 10 سال یا اس سے زائد",
    topics: [
      "آرٹیفیشل انٹیلیجنس (AI) کیا ہے",
      "AI کی تاریخ اور ارتقاء",
      "AI کی اقسام — Narrow، General، Super",
      "روزمرہ زندگی میں AI کا استعمال",
      "Machine Learning کے تصورات کا تعارف",
      "ڈیٹا اور AI — مشینیں کیسے سیکھتی ہیں",
      "عملی AI تجربات (Hands-on Experiments)",
      "اپنا پہلا AI پروجیکٹ بنانا",
    ],
    features: [
      "لائیو انٹرایکٹو کلاسز",
      "ہفتہ وار اسائنمنٹس",
      "عملی پروجیکٹس",
      "حقیقی دنیا کی مشق",
      "کورس کی تکمیل کا سرٹیفکیٹ",
      "WhatsApp کے ذریعے انسٹرکٹر کی سپورٹ",
    ],
    icon: "robot",
    color: "from-blue-500 to-cyan-400",
  },
  {
    slug: "intermediate-ai-course",
    title: "Intermediate AI Course — Machine Learning اور Data Science",
    shortTitle: "Intermediate AI کورس",
    description:
      "اپنی AI مہارتوں کو اگلے درجے پر لے جائیں۔ Machine Learning الگورتھمز، ڈیٹا اینالیسس، اور ماڈل بنانے کے عمل کو عملی پروجیکٹس کے ذریعے سیکھیں جو آپ کو حقیقی دنیا میں AI کے استعمال کے لیے تیار کرتے ہیں۔",
    level: "Intermediate",
    duration: "10 ہفتے",
    ageGroup: "عمر 13 سال یا اس سے زائد",
    topics: [
      "Machine Learning کے بنیادی اصول",
      "Supervised بمقابلہ Unsupervised Learning",
      "Classification اور Regression",
      "ڈیٹا کی پری پروسیسنگ اور صفائی (Data Preprocessing & Cleaning)",
      "Feature Engineering",
      "ماڈل کی ٹریننگ اور ایویلیوایشن (Evaluation)",
      "Neural Networks کا تعارف",
      "عملی ML پروجیکٹس",
    ],
    features: [
      "لائیو انٹرایکٹو کلاسز",
      "ہفتہ وار اسائنمنٹس",
      "عملی پروجیکٹس",
      "حقیقی دنیا کی مشق",
      "کورس کی تکمیل کا سرٹیفکیٹ",
      "WhatsApp کے ذریعے انسٹرکٹر کی سپورٹ",
    ],
    icon: "brain",
    color: "from-purple-500 to-pink-400",
  },
  {
    slug: "advanced-ai-course",
    title: "Advanced AI Course — Deep Learning اور Neural Networks",
    shortTitle: "Advanced AI کورس",
    description:
      "ایڈوانسڈ AI تصورات بشمول Deep Learning، Computer Vision اور Natural Language Processing (NLP) پر مہارت حاصل کریں۔ ایسی جدید ترین AI ایپلی کیشنز بنائیں جو حقیقی دنیا کے مسائل حل کریں۔",
    level: "Advanced",
    duration: "12 ہفتے",
    ageGroup: "عمر 15 سال یا اس سے زائد",
    topics: [
      "Deep Learning آرکیٹیکچرز",
      "Convolutional Neural Networks (CNN)",
      "Recurrent Neural Networks (RNN)",
      "Transfer Learning",
      "Computer Vision پروجیکٹس",
      "Natural Language Processing (NLP)",
      "ماڈل ڈیپلائمنٹ کے بنیادی اصول",
      "کیپسٹون (Capstone) AI پروجیکٹ",
    ],
    features: [
      "لائیو انٹرایکٹو کلاسز",
      "ہفتہ وار اسائنمنٹس",
      "عملی پروجیکٹس",
      "حقیقی دنیا کی مشق",
      "کورس کی تکمیل کا سرٹیفکیٹ",
      "WhatsApp کے ذریعے انسٹرکٹر کی سپورٹ",
    ],
    icon: "lightning",
    color: "from-orange-500 to-red-400",
  },
  {
    slug: "chatgpt-course",
    title: "ChatGPT Course — کنورسیشنل (Conversational) AI پر مہارت حاصل کریں",
    shortTitle: "ChatGPT کورس",
    description:
      "ChatGPT کو ایک پروفیشنل کی طرح استعمال کرنا سیکھیں۔ Prompt Engineering پر مہارت حاصل کریں، سمجھیں کہ Large Language Models کیسے کام کرتے ہیں، اور یہ جانیں کہ پڑھائی، تخلیقی صلاحیتوں اور کارکردگی کو بڑھانے کے لیے ChatGPT کو کیسے استعمال کیا جائے۔",
    level: "Beginner",
    duration: "6 ہفتے",
    ageGroup: "عمر 10 سال یا اس سے زائد",
    topics: [
      "ChatGPT اور LLMs کا تعارف",
      "ChatGPT کیسے کام کرتا ہے",
      "مؤثر پرامپٹ رائٹنگ (Prompt Writing)",
      "تعلیم اور تحقیق کے لیے ChatGPT کا استعمال",
      "تخلیقی تحریر (Creative Writing) کے لیے ChatGPT",
      "کوڈنگ میں مدد کے لیے ChatGPT",
      "AI اور ChatGPT کے اخلاقی پہلو (Ethics)",
      "ChatGPT سے چلنے والے پروجیکٹس بنانا",
    ],
    features: [
      "لائیو انٹرایکٹو کلاسز",
      "ہفتہ وار اسائنمنٹس",
      "عملی پروجیکٹس",
      "حقیقی دنیا کی مشق",
      "کورس کی تکمیل کا سرٹیفکیٹ",
      "WhatsApp کے ذریعے انسٹرکٹر کی سپورٹ",
    ],
    icon: "chat",
    color: "from-green-500 to-emerald-400",
  },
  {
    slug: "generative-ai-course",
    title: "Generative AI Course — آرٹیفیشل انٹیلیجنس کے ساتھ تخلیق کریں",
    shortTitle: "Generative AI کورس",
    description:
      "Generative AI کی دنیا کو دریافت کریں۔ AI ٹولز کا استعمال کرتے ہوئے تصاویر، ٹیکسٹ، میوزک، اور ویڈیوز بنانا سیکھیں۔ Diffusion Models، GANs، اور جدید ترین AI جنریشن ٹیکنالوجیز کو سمجھیں۔",
    level: "Intermediate",
    duration: "8 ہفتے",
    ageGroup: "عمر 12 سال یا اس سے زائد",
    topics: [
      "Generative AI کیا ہے",
      "AI کے ذریعے ٹیکسٹ جنریشن",
      "امیج جنریشن (Image Generation) — DALL-E، Midjourney، Stable Diffusion",
      "ویڈیو اور آڈیو جنریشن",
      "Diffusion Models کو سمجھنا",
      "GANs — Generative Adversarial Networks",
      "AI آرٹ اور تخلیقی ایپلی کیشنز",
      "Building Generative AI Projects",
    ],
    features: [
      "Live Interactive Classes",
      "Weekly Assignments",
      "Hands-on Projects",
      "Real World Practice",
      "Certificate of Completion",
      "Instructor Support via WhatsApp",
    ],
    icon: "palette",
    color: "from-violet-500 to-fuchsia-400",
  },
  {
    slug: "prompt-engineering-course",
    title: "Prompt Engineering Course — AI کے ساتھ گفتگو (Communication) پر مہارت حاصل کریں",
    shortTitle: "Prompt Engineering کورس",
    description:
      "Prompt Engineering کے فن اور سائنس کو سیکھیں۔ کسی بھی کام کے لیے ChatGPT، Claude، اور Gemini جیسے AI ماڈلز سے بہترین نتائج حاصل کرنے کی تکنیکوں پر مہارت حاصل کریں۔",
    level: "Beginner",
    duration: "6 ہفتے",
    ageGroup: "عمر 12 سال یا اس سے زائد",
    topics: [
      "Prompt Engineering کے بنیادی اصول",
      "پرامپٹ پیٹرنز اور ٹیمپلیٹس (Prompt Patterns and Templates)",
      "Zero-Shot بمقابلہ Few-Shot Prompting",
      "Chain of Thought Prompting",
      "Role-Based Prompting",
      "مختلف AI ٹولز کے لیے Prompt Engineering",
      "جدید پرامپٹنگ تکنیکیں (Advanced Prompting Techniques)",
      "حقیقی دنیا کے Prompt Engineering پروجیکٹس",
    ],
    features: [
      "Live Interactive Classes",
      "Weekly Assignments",
      "Hands-on Projects",
      "Real World Practice",
      "Certificate of Completion",
      "Instructor Support via WhatsApp",
    ],
    icon: "terminal",
    color: "from-teal-500 to-cyan-400",
  },
  {
    slug: "ai-tools-course",
    title: "AI Tools Course — طلباء کے لیے اہم ترین AI ٹولز",
    shortTitle: "AI Tools کورس",
    description:
      "آج دستیاب طاقتور ترین AI ٹولز کو دریافت کریں اور ان پر مہارت حاصل کریں۔ ChatGPT سے لے کر امیج جنریٹرز، کوڈنگ اسسٹنٹس اور تحقیقی ٹولز تک — ایسے AI ٹولز کا استعمال سیکھیں جو آپ کی کارکردگی کو بڑھاتے ہیں۔",
    level: "Beginner",
    duration: "6 ہفتے",
    ageGroup: "عمر 10 سال یا اس سے زائد",
    topics: [
      "جدید AI ٹولز کا جائزہ",
      "ChatGPT، Claude اور Gemini کا موازنہ",
      "AI امیج جنریشن ٹولز",
      "کوڈنگ کے لیے AI — GitHub Copilot اور دیگر",
      "تحقیق اور پڑھائی کے لیے AI ٹولز",
      "کنٹینٹ تخلیق کرنے کے لیے AI (Content Creation)",
      "پروڈکٹیوٹی بڑھانے والے AI ٹولز",
      "عملی AI ٹول پروجیکٹس",
    ],
    features: [
      "Live Interactive Classes",
      "Weekly Assignments",
      "Hands-on Projects",
      "Real World Practice",
      "Certificate of Completion",
      "Instructor Support via WhatsApp",
    ],
    icon: "tools",
    color: "from-amber-500 to-yellow-400",
  },
  {
    slug: "python-programming-course",
    title: "Python Programming Course — بالکل شروع سے پائتھن سیکھیں",
    shortTitle: "Python Programming کورس",
    description:
      "ہمارا Python Programming کورس مکمل طور پر نوآموزوں (beginners)، طلباء، پیشہ ور افراد، فری لانسرز، اور ہر اس شخص کے لیے ڈیزائن کیا گیا ہے جو بالکل بنیادی سطح سے پروگرامنگ سیکھنا چاہتا ہے۔ یہ کورس بنیادی باتوں سے شروع ہوتا ہے اور لائیو کلاسز، عملی مشقوں، کوڈنگ چیلنجز، اور حقیقی دنیا کے پروجیکٹس کے ذریعے بتدریج جدید تصورات کی طرف بڑھتا ہے۔ پروگرامنگ کا کوئی سابقہ تجربہ درکار نہیں ہے۔",
    level: "Beginner",
    duration: "2 ماہ",
    ageGroup: "عمر 10 سال یا اس سے زائد",
    topics: [
      "Python کے بنیادی اصول",
      "Variables اور Data Types",
      "Input اور Output",
      "Operators",
      "مشروط بیانات (Conditional Statements - if/else)",
      "Loops",
      "Functions",
      "Lists، Tuples اور Dictionaries",
      "فائل ہینڈلنگ (File Handling)",
      "Object-Oriented Programming (OOP)",
      "Error Handling",
      "Modules اور Packages",
      "حقیقی دنیا کے پروجیکٹس",
      "مسائل کا حل (Problem Solving) اور پروگرامنگ لاجک",
    ],
    features: [
      "لائیو آن لائن کلاسز",
      "بگینر فرینڈلی (Beginner Friendly)",
      "عملی کوڈنگ کی مشق (Hands-on Coding)",
      "حقیقی پروجیکٹس",
      "چھوٹے بیجز (Small Batches)",
      "انفرادی توجہ (Individual Attention)",
      "اسائنمنٹس اور پریکٹس مشقیں",
      "کورس کی تکمیل پر سرٹیفکیٹ",
    ],
    icon: "terminal",
    color: "from-blue-600 to-cyan-500",
    image: "/images/python-course.png",
  },
  {
    slug: "python-ai-development-course",
    title: "Python & AI Development — بالکل شروع سے حقیقی AI ایپس بنائیں",
    shortTitle: "Python اور AI ڈویلپمنٹ",
    description:
      "یہ کورس پائتھن پروگرامنگ میں ایک مضبوط بنیاد بنانے اور طلباء کو بتدریج عملی پائتھن ڈویلپمنٹ اور AI پر مبنی ایپلی کیشنز کی طرف لے جانے کے لیے ڈیزائن کیا گیا ہے۔ طلباء پائتھن کے بنیادی تصورات سیکھیں گے، انہیں عملی پروجیکٹس کے ذریعے لاگو کریں گے، AI خصوصیات کو شامل کریں گے، اور Streamlit کا استعمال کرتے ہوئے آسان ویب انٹرفیس بنائیں گے۔",
    level: "Beginner",
    duration: "2 ماہ",
    ageGroup: "عمر 12 سال یا اس سے زائد",
    topics: [
      "Python کے بنیادی اصول",
      "کنٹرول فلو اور فیصلے کرنے کا عمل (Control Flow & Decision Making)",
      "Functions اور دوبارہ استعمال کے قابل کوڈ (Reusable Code)",
      "ڈیٹا سٹرکچرز اور ڈکشنریز (Data Structures & Dictionaries)",
      "فائل ان پٹ/آؤٹ پٹ اور ماڈیولز (File Input/Output & Modules)",
      "Object-Oriented Programming (OOP)",
      "Pandas اور ڈیٹا اینالیسس کے بنیادی اصول",
      "قواعد پر مبنی اور AI سے چلنے والے چیٹ بوٹس (Rule-Based & AI-Powered Chatbots)",
      "Streamlit ویب انٹرفیسز",
      "AI + Streamlit مائیکرو (Mini) پروجیکٹس",
    ],
    features: [
      "لائیو آن لائن کلاسز (30 کلاسز)",
      "بگینر سے لے کر پروجیکٹ لیول تک",
      "عملی کوڈنگ کی مشق",
      "8 عملی پروجیکٹس",
      "چھوٹے بیجز اور انفرادی توجہ",
      "اسائنمنٹس اور پریکٹس مشقیں",
      "AI APIs اور انٹیگریشن (Integration)",
      "کورس کی تکمیل پر سرٹیفکیٹ",
    ],
    icon: "sparkles",
    color: "from-blue-600 to-emerald-500",
    image: "/images/python-ai-course.png",
    learningOutcomes: [
      "اعتماد کے ساتھ پائتھن پروگرام لکھنا اور بنیادی پروگرامنگ تصورات کو استعمال کرنا",
      "بنیادی سٹرکچرڈ ڈیٹا کے ساتھ کام کرنا اور Pandas لائبریری کا استعمال کرنا",
      "فنکشنز، ان پٹ، لوپس اور کنڈیشنز کو استعمال کرتے ہوئے انٹرایکٹو ڈیسک ٹاپ ایپلی کیشنز بنانا",
      "پائتھن اسکرپٹس کو جدید ترین AI ماڈل APIs (جیسے Gemini/OpenAI) کے ساتھ منسلک کرنا",
      "Streamlit کا استعمال کرتے ہوئے صاف اور فعال ویب پر مبنی یوزر انٹرفیس (UI) بنانا",
      "بالکل شروع سے مکمل طور پر فعال، AI سے چلنے والی ویب ایپلی کیشنز تیار کرنا",
    ],
    learningPath: [
      "Python کے بنیادی اصول",
      "مسائل کا حل (Problem Solving)",
      "عملی پروجیکٹس",
      "AI انٹیگریشن",
      "Streamlit",
      "AI سے چلنے والی ایپلی کیشنز",
    ],
    projects: [
      "پائتھن کیلکولیٹر (Python Calculator)",
      "ٹو-ڈو لسٹ ایپلی کیشن (To-Do List Application)",
      "نمبر کا اندازہ لگانے والی گیم (Number Guessing Game)",
      "کوئز ایپلی کیشن (Quiz Application)",
      "بنیادی قواعد پر مبنی چیٹ بوٹ (Rule-Based Chatbot)",
      "AI سے چلنے والا چیٹ بوٹ (AI-Powered Chatbot)",
      "Streamlit ویب ایپلی کیشن (Streamlit Web Application)",
      "AI + Streamlit مائیکرو پروجیکٹ",
    ],
    syllabus: [
      {
        partTitle: "حصہ 1: پائتھن کے بنیادی اصول (کلاسز 1 تا 20)",
        classes: [
          {
            number: 1,
            title: "پائتھن کا تعارف",
            bullets: [
              "پائتھن کیا ہے اور یہ اتنے بڑے پیمانے پر کیوں استعمال ہوتی ہے",
              "پائتھن کی ایپلی کیشنز اور ڈویلپمنٹ انوائرمنٹس (Development Environments)",
              "پہلا پائتھن پروگرام لکھنا اور چلانا",
              "print() فنکشن",
            ],
          },
          {
            number: 2,
            title: "Variables اور Data Types",
            bullets: [
              "Variables اور نام رکھنے کے اصول (Naming Conventions)",
              "Strings، integers، floats اور booleans",
              "بنیادی ٹائپ کنورژن (Type Conversion)",
              "عملی مشقیں",
            ],
          },
          {
            number: 3,
            title: "Input اور Output",
            bullets: [
              "input() کے ذریعے یوزر سے ان پٹ لینا",
              "آؤٹ پٹ کو فارمیٹ کرنا",
              "انٹرایکٹو پائتھن پروگرامز",
              "عملی مشقیں",
            ],
          },
          {
            number: 4,
            title: "Operators",
            bullets: [
              "Arithmetic، comparison اور logical آپریٹرز",
              "اسائنمنٹ آپریٹرز (Assignment Operators)",
              "پروگراموں میں مختلف آپریٹرز کا امتزاج (Combining Operators)",
              "عملی مثالیں",
            ],
          },
          {
            number: 5,
            title: "مشروط بیانات (Conditional Statements)",
            bullets: [
              "if، elif اور else",
              "نیسٹڈ کنڈیشنز (Nested Conditions)",
              "فیصلے کرنے والے پروگرام (Decision-making programs)",
              "عملی مشقیں",
            ],
          },
          {
            number: 6,
            title: "Loops",
            bullets: [
              "for اور while لوپس",
              "لوپ کنٹرول (break, continue)",
              "کاموں کو مؤثر طریقے سے دہرانا",
              "عملی مشقیں",
            ],
          },
          {
            number: 7,
            title: "Lists",
            bullets: [
              "Lists بنانا اور ان تک رسائی حاصل کرنا",
              "ایلیمنٹس کو شامل کرنا، ہٹانا اور اپ ڈیٹ کرنا",
              "لسٹ کے مختلف میتھڈز (List methods)",
              "عملی مشقیں",
            ],
          },
          {
            number: 8,
            title: "Tuples اور Sets",
            bullets: [
              "Tuples اور sets کا تعارف",
              "Lists سے اہم اختلافات",
              "کون سا ڈیٹا سٹرکچر کب استعمال کیا جائے",
              "عملی مثالیں",
            ],
          },
          {
            number: 9,
            title: "Dictionaries",
            bullets: [
              "Keys اور values کا تصور",
              "Dictionaries بنانا اور اپ ڈیٹ کرنا",
              "ڈکشنری کے ڈیٹا تک رسائی حاصل کرنا",
              "عملی مشقیں",
            ],
          },
          {
            number: 10,
            title: "پائتھن میں Strings",
            bullets: [
              "انڈیکسنگ اور سلائسنگ (Indexing & Slicing)",
              "عام استعمال ہونے والے سٹرنگ میتھڈز",
              "سٹرنگ کی فارمیٹنگ",
              "ٹیکسٹ پروسیسنگ (Text-processing) کی مشقیں",
            ],
          },
          {
            number: 11,
            title: "Functions",
            bullets: [
              "Functions بنانا",
              "Parameters اور arguments",
              "ریٹرن ویلیوز (Return values)",
              "دوبارہ استعمال ہونے والا کوڈ (Reusable code)",
            ],
          },
          {
            number: 12,
            title: "فنکشن کے تصورات",
            bullets: [
              "ڈیفالٹ پیرامیٹرز (Default parameters)",
              "متعدد پیرامیٹرز (Multiple parameters)",
              "ویری ایبل اسکوپ (Variable scope)",
              "فنکشنز پر مبنی پروگرامز",
            ],
          },
          {
            number: 13,
            title: "Error Handling",
            bullets: [
              "پائتھن میں عام غلطیاں (Common Errors)",
              "try، except اور finally",
              "غلط ان پٹ (Invalid Input) کو سنبھالنا",
              "زیادہ قابل اعتماد پروگرام لکھنا",
            ],
          },
          {
            number: 14,
            title: "فائل ہینڈلنگ (File Handling)",
            bullets: [
              "ٹیکسٹ فائلوں کو پڑھنا اور لکھنا",
              "فائل کا مواد اپ ڈیٹ کرنا",
              "فائلوں پر مبنی عملی پروگرام",
              "ڈیٹا اسٹوریج کے بنیادی اصول",
            ],
          },
          {
            number: 15,
            title: "Modules",
            bullets: [
              "ماڈیولز کیا ہیں؟",
              "بلٹ ان ماڈیولز کو امپورٹ کرنا",
              "بیرونی (External) ماڈیولز کا استعمال",
              "دوبارہ استعمال ہونے والی پائتھن فائلیں بنانا",
            ],
          },
          {
            number: 16,
            title: "پائتھن لائبریریاں (Python Libraries)",
            bullets: [
              "لائبریریاں اور پیکجز کیا ہیں؟",
              "پیکجز انسٹال کرنا",
              "مفید پائتھن لائبریریوں کا استعمال",
              "عملی مثالیں",
            ],
          },
          {
            number: 17,
            title: "Object-Oriented Programming (OOP) کے بنیادی اصول",
            bullets: [
              "Classes اور objects",
              "Attributes اور methods",
              "بنیادی OOP سٹرکچر",
              "آسان عملی مثال",
            ],
          },
          {
            number: 18,
            title: "ڈیٹا کے ساتھ کام کرنا (Working with Data)",
            bullets: [
              "سٹرکچرڈ ڈیٹا کا تعارف",
              "CSV فائلیں",
              "ڈیٹا پروسیسنگ کے بنیادی اصول",
              "Pandas کا تعارف",
            ],
          },
          {
            number: 19,
            title: "پائتھن اور AI کا تعارف",
            bullets: [
              "AI کیا ہے؟",
              "پائتھن AI میں کیسے استعمال ہوتی ہے",
              "AI ٹولز اور APIs کا تعارف",
              "بنیادی AI سے چلنے والا پائتھن پروگرام بنانا",
            ],
          },
          {
            number: 20,
            title: "پائتھن کے بنیادی اصولوں کی پریکٹس",
            bullets: [
              "مکمل دہرائی (Revision)",
              "مسائل کو حل کرنے کی مشقیں",
              "کوڈنگ چیلنجز",
              "چھوٹے عملی کام",
            ],
          },
        ],
      },
      {
        partTitle: "حصہ 2: پائتھن ڈویلپمنٹ اور AI پروجیکٹس (کلاسز 21 تا 30)",
        classes: [
          {
            number: 21,
            title: "پروجیکٹ 1: پائتھن کیلکولیٹر",
            bullets: [
              "ایک فعال کیلکولیٹر بنانا",
              "فنکشنز، ان پٹ، شرائط (conditions) اور آپریٹرز کا استعمال",
              "ایپلی کیشن کی جانچ اور اس میں بہتری",
            ],
          },
          {
            number: 22,
            title: "پروجیکٹ 2: ٹو-ڈو لسٹ ایپ",
            bullets: [
              "کاموں کو شامل کرنا، دیکھنا اور ہٹانا",
              "Lists اور functions کا عملی اطلاق",
              "ٹاسک ڈیٹا کو اسٹور اور مینیج کرنا",
            ],
          },
          {
            number: 23,
            title: "پروجیکٹ 3: نمبر کا اندازہ لگانے والی گیم",
            bullets: [
              "رینڈم (Random) نمبرز کا استعمال",
              "Loops اور conditions کا اطلاق",
              "انٹرایکٹو گیم لاجک بنانا",
            ],
          },
          {
            number: 24,
            title: "پروجیکٹ 4: کوئز ایپلی کیشن",
            bullets: [
              "سوالات اور جوابات بنانا",
              "جوابات کی جانچ کرنا",
              "اسکور کا حساب لگانا",
              "ایک انٹرایکٹو کوئز بنانا",
            ],
          },
          {
            number: 25,
            title: "پروجیکٹ 5: بنیادی پائتھن چیٹ بوٹ",
            bullets: [
              "چیٹ بوٹ کی لاجک کو سمجھنا",
              "یوزر کے ان پٹ کو پروسیس کرنا",
              "قواعد پر مبنی (Rule-based) جوابات تیار کرنا",
              "ایک سادہ چیٹ بوٹ بنانا",
            ],
          },
          {
            number: 26,
            title: "AI سے چلنے والا چیٹ بوٹ",
            bullets: [
              "AI APIs کا تعارف",
              "پائتھن کو AI ماڈل کے ساتھ منسلک کرنا",
              "پرامپٹس بھیجنا اور جوابات وصول کرنا",
              "ایک سادہ AI چیٹ بوٹ بنانا",
            ],
          },
          {
            number: 27,
            title: "Streamlit کا تعارف",
            bullets: [
              "Streamlit کیا ہے؟",
              "پائتھن کا استعمال کرتے ہوئے ویب انٹرفیس بنانا",
              "ٹیکسٹ، بٹنز اور ان پٹ فیلڈز کا استعمال",
              "Streamlit ایپلی کیشن کو رن کرنا",
            ],
          },
          {
            number: 28,
            title: "Streamlit ایپلی کیشن بنانا",
            bullets: [
              "ایک مکمل انٹرفیس ڈیزائن کرنا",
              "ان پٹ فیلڈز، بٹنز اور ڈراپ ڈاؤنز کا استعمال",
              "نتائج کو ظاہر کرنا",
              "پائتھن لاجک کو انٹرفیس کے ساتھ جوڑنا",
            ],
          },
          {
            number: 29,
            title: "AI + Streamlit مائیکرو پروجیکٹ",
            bullets: [
              "Python، AI اور Streamlit کو یکجا کرنا",
              "ایک AI سے چلنے والی ایپلی کیشن بنانا",
              "یوزر انٹرفیس (UI) تیار کرنا",
              "AI فنکشنلٹی کو جوڑنا اور ٹیسٹ کرنا",
            ],
          },
          {
            number: 30,
            title: "فائنل پروجیکٹ اور کورس شوکیس",
            bullets: [
              "فائنل پروجیکٹ تیار کرنا اور اس کا ٹیسٹ کرنا",
              "ایپلی کیشن کی غلطیاں دور کرنا اور بہتر بنانا",
              "مکمل شدہ پروجیکٹ پیش کرنا",
              "سیکھنے کے اگلے مراحل پر تبادلہ خیال",
            ],
          },
        ],
      },
    ],
  },
];
